### ISSUE TITLE
Running upgradeDependencies as a GitHub Action

### ISSUE THREAD

**Issue by KushalP** [releaseshub/releases-hub-gradle-plugin#87]
## Is your feature request related to a problem? Please describe.

Running `upgradeDependencies` should be possible on a cron schedule, using the simplest tooling available. GitHub has Actions, and they have access to a `GITHUB_TOKEN` for interacting with the GitHub API.

## Describe the solution you'd like

It is easy to run `upgradeDependencies` using GitHub Actions on a cron schedule (weekly?)

## Describe alternatives you've considered

We could run this on Jenkins, but that involves more tooling.

## Additional context

Example configuration of a GitHub Action:

```yaml
---
on:
  schedule:
    - cron: '0 09 * * 1-5'
name: upgradeDependencies
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: upgradeDependencies
        run: ./gradlew --no-daemon upgradeDependencies -PbaseBranch="master" -PpullRequestEnabled=true -PgitHubWriteToken=${{ secrets.GITHUB_TOKEN }}
```
